### ISSUE TITLE
Search the library catalog

### ISSUE THREAD

**Issue by dranidis** [dranidis/test-repository#18]
# Story
- As a library member, I want to be able to search the library catalog by title, author, or subject so that I can quickly find the books I am interested in.

# Tasks
- [ ] Create UI form for searching
- [ ] Implement search BE
- [ ] Implement search FE
